[build]
  publish = "build"
  command = "pip install -r requirements.txt && python freeze.py"

[build.environment]
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
